services:
  daemon:
    image: horde.home:5000/shazam-daemon:latest
    restart: on-failure
    pull_policy: always
    platform: linux/arm64
    user: "USER_ID:GROUP_ID"
    env_file:
      - /app/shazam/.env
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /app/shazam/data:/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw